Regenerate .travis.yml using latest haskell-ci, #89.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,82 +1,171 @@
-# This is the simple Travis configuration, which is intended for use
-# on applications which do not require cross-platform and
-# multiple-GHC-version support. For more information and other
-# options, see:
+# This Travis job script has been generated by a script via
 #
-# https://docs.haskellstack.org/en/stable/travis_ci/
+#   runghc make_travis_yml_2.hs '--output=.travis.yml' '--config=cabal.haskell-ci' 'cabal.project'
 #
-# Copy these contents into the root directory of your Github project in a file
-# named .travis.yml
-
-# Use new container infrastructure to enable caching
+# For more information, see https://github.com/haskell-CI/haskell-ci
+#
+language: c
 sudo: false
 
-# Do not choose a language; we provide our own build tools.
-language: generic
+git:
+  submodules: false  # whether to recursively clone submodules
 
-# Caching so the next build will be fast too.
 cache:
   directories:
-  - $HOME/.stack
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
 
-# Ensure necessary system libraries are present
-addons:
-  apt:
-    packages:
-      - libgmp-dev
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
+
+  - rm -rfv $HOME/.cabal/packages/head.hackage
+
+matrix:
+  include:
+    - compiler: "ghc-8.2.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.2.2], sources: [hvr-ghc]}}
 
 before_install:
-# To avoid running out of memory, add a swap file.
-# SEE: https://www.reddit.com/r/haskell/comments/5ov5k1/how_to_stack_build_specifically_lens_on_a_low/
-# - sudo mkdir -v /var/cache/swap
-# - cd /var/cache/swap
-# - sudo dd if=/dev/zero of=swapfile bs=1K count=4M
-# - sudo chmod 600 swapfile
-# - sudo mkswap swapfile
-# - sudo swapon swapfile
-# Download and unpack the stack executable
-- mkdir -p ~/.local/bin
-- export PATH=$HOME/.local/bin:$PATH
-- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
+  - HC=${CC}
+  - HCPKG=${HC/ghc/ghc-pkg}
+  - unset CC
+  - ROOTDIR=$(pwd)
+  - mkdir -p $HOME/.local/bin
+  - "PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$HOME/local/bin:$PATH"
+  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
+  - echo $HCNUMVER
 
 install:
-- stack build build-flare-timing --only-dependencies --install-ghc --no-terminal
-- stack install dhall hpack-dhall --no-terminal
-- stack test flare-timing --only-dependencies --no-terminal
+  - cabal --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - BENCH=${BENCH---enable-benchmarks}
+  - TEST=${TEST---enable-tests}
+  - HADDOCK=${HADDOCK-true}
+  - UNCONSTRAINED=${UNCONSTRAINED-true}
+  - NOINSTALLEDCONSTRAINTS=${NOINSTALLEDCONSTRAINTS-false}
+  - GHCHEAD=${GHCHEAD-false}
+  - travis_retry cabal update -v
+  - "sed -i.bak 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config"
+  - rm -fv cabal.project cabal.project.local
+  - grep -Ev -- '^\s*--' ${HOME}/.cabal/config | grep -Ev '^\s*$'
+  - "printf 'packages: \"build\" \"detour-via-sci\" \"detour-via-uom\" \"cmd\" \"comp\" \"earth\" \"fsdb\" \"gap\" \"igc\" \"kml\" \"latlng\" \"lookup\" \"mask\" \"route\" \"scribe\" \"siggy-chardust\" \"span\" \"task\" \"tasty-compare\" \"track\" \"units\" \"zone\" \"flare-timing\" \".stack2cabal/hcoord/hcoord\" \".stack2cabal/hcoord/hcoord-utm\"\\n' > cabal.project"
+  - touch cabal.project.local
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- build-flare-timing | grep -vw -- detour-via-sci | grep -vw -- detour-via-uom | grep -vw -- flight-cmd | grep -vw -- flight-comp | grep -vw -- flight-earth | grep -vw -- flight-fsdb | grep -vw -- flight-gap | grep -vw -- flight-igc | grep -vw -- flight-kml | grep -vw -- flight-latlng | grep -vw -- flight-lookup | grep -vw -- flight-mask | grep -vw -- flight-route | grep -vw -- flight-scribe | grep -vw -- siggy-chardust | grep -vw -- flight-span | grep -vw -- flight-task | grep -vw -- tasty-compare | grep -vw -- flight-track | grep -vw -- flight-units | grep -vw -- flight-zone | grep -vw -- flare-timing | grep -vw -- hcoord | grep -vw -- hcoord-utm | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  - if [ -f "build/configure.ac" ]; then
+      (cd "build" && autoreconf -i);
+    fi
+  - if [ -f "detour-via-sci/configure.ac" ]; then
+      (cd "detour-via-sci" && autoreconf -i);
+    fi
+  - if [ -f "detour-via-uom/configure.ac" ]; then
+      (cd "detour-via-uom" && autoreconf -i);
+    fi
+  - if [ -f "cmd/configure.ac" ]; then
+      (cd "cmd" && autoreconf -i);
+    fi
+  - if [ -f "comp/configure.ac" ]; then
+      (cd "comp" && autoreconf -i);
+    fi
+  - if [ -f "earth/configure.ac" ]; then
+      (cd "earth" && autoreconf -i);
+    fi
+  - if [ -f "fsdb/configure.ac" ]; then
+      (cd "fsdb" && autoreconf -i);
+    fi
+  - if [ -f "gap/configure.ac" ]; then
+      (cd "gap" && autoreconf -i);
+    fi
+  - if [ -f "igc/configure.ac" ]; then
+      (cd "igc" && autoreconf -i);
+    fi
+  - if [ -f "kml/configure.ac" ]; then
+      (cd "kml" && autoreconf -i);
+    fi
+  - if [ -f "latlng/configure.ac" ]; then
+      (cd "latlng" && autoreconf -i);
+    fi
+  - if [ -f "lookup/configure.ac" ]; then
+      (cd "lookup" && autoreconf -i);
+    fi
+  - if [ -f "mask/configure.ac" ]; then
+      (cd "mask" && autoreconf -i);
+    fi
+  - if [ -f "route/configure.ac" ]; then
+      (cd "route" && autoreconf -i);
+    fi
+  - if [ -f "scribe/configure.ac" ]; then
+      (cd "scribe" && autoreconf -i);
+    fi
+  - if [ -f "siggy-chardust/configure.ac" ]; then
+      (cd "siggy-chardust" && autoreconf -i);
+    fi
+  - if [ -f "span/configure.ac" ]; then
+      (cd "span" && autoreconf -i);
+    fi
+  - if [ -f "task/configure.ac" ]; then
+      (cd "task" && autoreconf -i);
+    fi
+  - if [ -f "tasty-compare/configure.ac" ]; then
+      (cd "tasty-compare" && autoreconf -i);
+    fi
+  - if [ -f "track/configure.ac" ]; then
+      (cd "track" && autoreconf -i);
+    fi
+  - if [ -f "units/configure.ac" ]; then
+      (cd "units" && autoreconf -i);
+    fi
+  - if [ -f "zone/configure.ac" ]; then
+      (cd "zone" && autoreconf -i);
+    fi
+  - if [ -f "flare-timing/configure.ac" ]; then
+      (cd "flare-timing" && autoreconf -i);
+    fi
+  - if [ -f ".stack2cabal/hcoord/hcoord/configure.ac" ]; then
+      (cd ".stack2cabal/hcoord/hcoord" && autoreconf -i);
+    fi
+  - if [ -f ".stack2cabal/hcoord/hcoord-utm/configure.ac" ]; then
+      (cd ".stack2cabal/hcoord/hcoord-utm" && autoreconf -i);
+    fi
+  - rm -f cabal.project.freeze
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --project-file="cabal.project" --dep -j2 all
+  - rm -rf .ghc.environment.* "build"/dist "detour-via-sci"/dist "detour-via-uom"/dist "cmd"/dist "comp"/dist "earth"/dist "fsdb"/dist "gap"/dist "igc"/dist "kml"/dist "latlng"/dist "lookup"/dist "mask"/dist "route"/dist "scribe"/dist "siggy-chardust"/dist "span"/dist "task"/dist "tasty-compare"/dist "track"/dist "units"/dist "zone"/dist "flare-timing"/dist ".stack2cabal/hcoord/hcoord"/dist ".stack2cabal/hcoord/hcoord-utm"/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
 
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-# Build the package, its tests, and its docs and run the tests
-- stack build build-flare-timing --no-terminal
-- ./stack-shake-build.sh cabal-files
-- ./stack-shake-build.sh stack-test-apps
-- ./stack-shake-build.sh stack-prod-apps
-# NOTE: The stack-lint target is timing out on travis-ci.org
-# The job exceeded the maximum time limit for jobs, and has been terminated.
-# - ./stack-shake-build.sh stack-lint
-# Let's try them as separate targets.
- - ./stack-shake-build.sh stack-lint-build
- - ./stack-shake-build.sh stack-lint-detour-via-sci
- - ./stack-shake-build.sh stack-lint-detour-via-uom
- - ./stack-shake-build.sh stack-lint-siggy-chardust
- - ./stack-shake-build.sh stack-lint-tasty-compare
- - ./stack-shake-build.sh stack-lint-flare-timing
- - ./stack-shake-build.sh stack-lint-cmd
- - ./stack-shake-build.sh stack-lint-comp
- - ./stack-shake-build.sh stack-lint-earth
- - ./stack-shake-build.sh stack-lint-fsdb
- - ./stack-shake-build.sh stack-lint-gap
- - ./stack-shake-build.sh stack-lint-igc
- - ./stack-shake-build.sh stack-lint-kml
- - ./stack-shake-build.sh stack-lint-latlng
- - ./stack-shake-build.sh stack-lint-lookup
- - ./stack-shake-build.sh stack-lint-mask
- - ./stack-shake-build.sh stack-lint-route
- - ./stack-shake-build.sh stack-lint-span
- - ./stack-shake-build.sh stack-lint-scribe
- - ./stack-shake-build.sh stack-lint-task
- - ./stack-shake-build.sh stack-lint-track
- - ./stack-shake-build.sh stack-lint-units
- - ./stack-shake-build.sh stack-lint-zone
-# NOTE: Building the test suites is timing out on travis-ci.org
-# The job exceeded the maximum time limit for jobs, and has been terminated.
-# - ./stack-shake-build.sh stack-test-suites
+  # test that source-distributions can be generated
+  - cabal new-sdist all
+  - mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
+  - cd ${DISTDIR} || false
+  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - "printf 'packages: build-flare-timing-*/*.cabal detour-via-sci-*/*.cabal detour-via-uom-*/*.cabal flight-cmd-*/*.cabal flight-comp-*/*.cabal flight-earth-*/*.cabal flight-fsdb-*/*.cabal flight-gap-*/*.cabal flight-igc-*/*.cabal flight-kml-*/*.cabal flight-latlng-*/*.cabal flight-lookup-*/*.cabal flight-mask-*/*.cabal flight-route-*/*.cabal flight-scribe-*/*.cabal siggy-chardust-*/*.cabal flight-span-*/*.cabal flight-task-*/*.cabal tasty-compare-*/*.cabal flight-track-*/*.cabal flight-units-*/*.cabal flight-zone-*/*.cabal flare-timing-*/*.cabal hcoord-*/*.cabal hcoord-utm-*/*.cabal\\n' > cabal.project"
+  - touch cabal.project.local
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- build-flare-timing | grep -vw -- detour-via-sci | grep -vw -- detour-via-uom | grep -vw -- flight-cmd | grep -vw -- flight-comp | grep -vw -- flight-earth | grep -vw -- flight-fsdb | grep -vw -- flight-gap | grep -vw -- flight-igc | grep -vw -- flight-kml | grep -vw -- flight-latlng | grep -vw -- flight-lookup | grep -vw -- flight-mask | grep -vw -- flight-route | grep -vw -- flight-scribe | grep -vw -- siggy-chardust | grep -vw -- flight-span | grep -vw -- flight-task | grep -vw -- tasty-compare | grep -vw -- flight-track | grep -vw -- flight-units | grep -vw -- flight-zone | grep -vw -- flare-timing | grep -vw -- hcoord | grep -vw -- hcoord-utm | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  # this builds all libraries and executables (without tests/benchmarks)
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
+
+  # build & run tests, build benchmarks
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+  - if [ "x$TEST" = "x--enable-tests" ]; then cabal new-test -w ${HC} ${TEST} ${BENCH} all; fi
+
+  # haddock
+  - if $HADDOCK; then cabal new-haddock -w ${HC} ${TEST} ${BENCH} all; else echo "Skipping haddock generation";fi
+
+  # Build without installed constraints for packages in global-db
+  - if $UNCONSTRAINED; then rm -f cabal.project.local; echo cabal new-build -w ${HC} --disable-tests --disable-benchmarks all; else echo "Not building without installed constraints"; fi
+
+# REGENDATA ["--output=.travis.yml","--config=cabal.haskell-ci","cabal.project"]
+# EOF
