Add tested-with to pkgs and generate .travis.yml, #10.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,177 +1,201 @@
-# This is the complex Travis configuration, which is intended for use
-# on open source libraries which need compatibility across multiple GHC
-# versions, must work with cabal-install, and should be
-# cross-platform. For more information and other options, see:
+# This Travis job script has been generated by a script via
 #
-# https://docs.haskellstack.org/en/stable/travis_ci/
+#   runghc make_travis_yml_2.hs 'cabal.project'
 #
-# Copy these contents into the root directory of your Github project in a file
-# named .travis.yml
-
-# Use new container infrastructure to enable caching
+# For more information, see https://github.com/hvr/multi-ghc-travis
+#
+language: c
 sudo: false
 
-# Do not choose a language; we provide our own build tools.
-language: generic
+git:
+  submodules: false  # whether to recursively clone submodules
 
-# Caching so the next build will be fast too.
 cache:
   directories:
-  - $HOME/.ghc
-  - $HOME/.cabal
-  - $HOME/.stack
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
 
-branches:
-  only:
-    - master
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
 
-# The different configurations we want to test. We have BUILD=cabal which uses
-# cabal-install, and BUILD=stack which uses Stack. More documentation on each
-# of those below.
-#
-# We set the compiler values here to tell Travis to use a different
-# cache file per set of arguments.
-#
-# If you need to have different apt packages for each combination in the
-# matrix, you can use a line such as:
-#     addons: {apt: {packages: [libfcgi-dev,libgmp-dev]}}
+  - rm -rfv $HOME/.cabal/packages/head.hackage
+
 matrix:
   include:
-  # We grab the appropriate GHC and cabal-install versions from hvr's PPA. See:
-  # https://github.com/hvr/multi-ghc-travis
-
-  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
-  # variable, such as using --stack-yaml to point to a different file.
-  - env: BUILD=stack ARGS=""
-    compiler: ": #stack default"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: BUILD=stack ARGS="--resolver lts-3"
-    compiler: ": #stack 7.10.2"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: BUILD=stack ARGS="--resolver lts-6"
-    compiler: ": #stack 7.10.3"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: BUILD=stack ARGS="--resolver lts-7"
-    compiler: ": #stack 8.0.1"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  - env: BUILD=stack ARGS="--resolver lts-8"
-    compiler: ": #stack 8.0.2"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  # Nightly builds are allowed to fail
-  - env: BUILD=stack ARGS="--resolver nightly"
-    compiler: ": #stack nightly"
-    addons: {apt: {packages: [libgmp-dev]}}
-
-  # Build on macOS in addition to Linux
-  - env: BUILD=stack ARGS=""
-    compiler: ": #stack default osx"
-    os: osx
-
-  - env: BUILD=stack ARGS="--resolver lts-3"
-    compiler: ": #stack 7.10.2 osx"
-    os: osx
-
-  - env: BUILD=stack ARGS="--resolver lts-6"
-    compiler: ": #stack 7.10.3 osx"
-    os: osx
-
-  - env: BUILD=stack ARGS="--resolver lts-7"
-    compiler: ": #stack 8.0.1 osx"
-    os: osx
-
-  - env: BUILD=stack ARGS="--resolver lts-8"
-    compiler: ": #stack 8.0.2 osx"
-    os: osx
-
-  - env: BUILD=stack ARGS="--resolver nightly"
-    compiler: ": #stack nightly osx"
-    os: osx
-
-  allow_failures:
-  - env: BUILD=cabal GHCVER=head  CABALVER=head HAPPYVER=1.19.5 ALEXVER=3.1.7
-  - env: BUILD=stack ARGS="--resolver nightly"
+    - compiler: "ghc-8.2.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-head,ghc-8.2.2], sources: [hvr-ghc]}}
 
 before_install:
-# Using compiler above sets CC to an invalid value, so unset it
-- unset CC
-
-# We want to always allow newer versions of packages when building on GHC HEAD
-- CABALARGS=""
-- if [ "x$GHCVER" = "xhead" ]; then CABALARGS=--allow-newer; fi
-
-# Download and unpack the stack executable
-- export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
-- mkdir -p ~/.local/bin
-- |
-  if [ `uname` = "Darwin" ]
-  then
-    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
-  else
-    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
-  fi
-
-  # Use the more reliable S3 mirror of Hackage
-  mkdir -p $HOME/.cabal
-  echo 'remote-repo: hackage.haskell.org:http://hackage.fpcomplete.com/' > $HOME/.cabal/config
-  echo 'remote-repo-cache: $HOME/.cabal/packages' >> $HOME/.cabal/config
-
-  if [ "$CABALVER" != "1.16" ]
-  then
-    echo 'jobs: $ncpus' >> $HOME/.cabal/config
-  fi
+  - HC=${CC}
+  - HCPKG=${HC/ghc/ghc-pkg}
+  - unset CC
+  - ROOTDIR=$(pwd)
+  - mkdir -p $HOME/.local/bin
+  - "PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$HOME/local/bin:$PATH"
+  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
+  - echo $HCNUMVER
 
 install:
-- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
-- if [ -f configure.ac ]; then autoreconf -i; fi
-- |
-  set -ex
-  case "$BUILD" in
-    stack)
-      stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
-      ;;
-    cabal)
-      cabal --version
-      travis_retry cabal update
+  - cabal --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - BENCH=${BENCH---enable-benchmarks}
+  - TEST=${TEST---enable-tests}
+  - HADDOCK=${HADDOCK-true}
+  - INSTALLED=${INSTALLED-true}
+  - GHCHEAD=${GHCHEAD-false}
+  - travis_retry cabal update -v
+  - "sed -i.bak 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config"
+  - rm -fv cabal.project cabal.project.local
+  - grep -Ev -- '^\s*--' ${HOME}/.cabal/config | grep -Ev '^\s*$'
+  - "printf 'packages: \"build\" \"aeson-via-sci\" \"aeson-via-uom\" \"cmd\" \"comp\" \"earth\" \"fsdb\" \"gap\" \"igc\" \"kml\" \"latlng\" \"lookup\" \"mask\" \"route\" \"scribe\" \"siggy-chardust\" \"span\" \"task\" \"tasty-compare\" \"track\" \"units\" \"zone\"\\n' > cabal.project"
+  - cat cabal.project
+  - if [ -f "build/configure.ac" ]; then
+      (cd "build" && autoreconf -i);
+    fi
+  - if [ -f "aeson-via-sci/configure.ac" ]; then
+      (cd "aeson-via-sci" && autoreconf -i);
+    fi
+  - if [ -f "aeson-via-uom/configure.ac" ]; then
+      (cd "aeson-via-uom" && autoreconf -i);
+    fi
+  - if [ -f "cmd/configure.ac" ]; then
+      (cd "cmd" && autoreconf -i);
+    fi
+  - if [ -f "comp/configure.ac" ]; then
+      (cd "comp" && autoreconf -i);
+    fi
+  - if [ -f "earth/configure.ac" ]; then
+      (cd "earth" && autoreconf -i);
+    fi
+  - if [ -f "fsdb/configure.ac" ]; then
+      (cd "fsdb" && autoreconf -i);
+    fi
+  - if [ -f "gap/configure.ac" ]; then
+      (cd "gap" && autoreconf -i);
+    fi
+  - if [ -f "igc/configure.ac" ]; then
+      (cd "igc" && autoreconf -i);
+    fi
+  - if [ -f "kml/configure.ac" ]; then
+      (cd "kml" && autoreconf -i);
+    fi
+  - if [ -f "latlng/configure.ac" ]; then
+      (cd "latlng" && autoreconf -i);
+    fi
+  - if [ -f "lookup/configure.ac" ]; then
+      (cd "lookup" && autoreconf -i);
+    fi
+  - if [ -f "mask/configure.ac" ]; then
+      (cd "mask" && autoreconf -i);
+    fi
+  - if [ -f "route/configure.ac" ]; then
+      (cd "route" && autoreconf -i);
+    fi
+  - if [ -f "scribe/configure.ac" ]; then
+      (cd "scribe" && autoreconf -i);
+    fi
+  - if [ -f "siggy-chardust/configure.ac" ]; then
+      (cd "siggy-chardust" && autoreconf -i);
+    fi
+  - if [ -f "span/configure.ac" ]; then
+      (cd "span" && autoreconf -i);
+    fi
+  - if [ -f "task/configure.ac" ]; then
+      (cd "task" && autoreconf -i);
+    fi
+  - if [ -f "tasty-compare/configure.ac" ]; then
+      (cd "tasty-compare" && autoreconf -i);
+    fi
+  - if [ -f "track/configure.ac" ]; then
+      (cd "track" && autoreconf -i);
+    fi
+  - if [ -f "units/configure.ac" ]; then
+      (cd "units" && autoreconf -i);
+    fi
+  - if [ -f "zone/configure.ac" ]; then
+      (cd "zone" && autoreconf -i);
+    fi
+  - rm -f cabal.project.freeze
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --project-file="cabal.project" --dep -j2 all
+  - rm -rf .ghc.environment.* "build"/dist "aeson-via-sci"/dist "aeson-via-uom"/dist "cmd"/dist "comp"/dist "earth"/dist "fsdb"/dist "gap"/dist "igc"/dist "kml"/dist "latlng"/dist "lookup"/dist "mask"/dist "route"/dist "scribe"/dist "siggy-chardust"/dist "span"/dist "task"/dist "tasty-compare"/dist "track"/dist "units"/dist "zone"/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
 
-      # Get the list of packages from the stack.yaml file
-      PACKAGES=$(stack --install-ghc query locals | grep '^ *path' | sed 's@^ *path:@@')
-
-      cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES
-      ;;
-  esac
-  set +ex
-
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
 script:
-- |
-  set -ex
-  case "$BUILD" in
-    stack)
-      stack --no-terminal $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
-      ;;
-    cabal)
-      cabal install --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES
+  # test that source-distributions can be generated
+  - (cd "build" && cabal sdist)
+  - (cd "aeson-via-sci" && cabal sdist)
+  - (cd "aeson-via-uom" && cabal sdist)
+  - (cd "cmd" && cabal sdist)
+  - (cd "comp" && cabal sdist)
+  - (cd "earth" && cabal sdist)
+  - (cd "fsdb" && cabal sdist)
+  - (cd "gap" && cabal sdist)
+  - (cd "igc" && cabal sdist)
+  - (cd "kml" && cabal sdist)
+  - (cd "latlng" && cabal sdist)
+  - (cd "lookup" && cabal sdist)
+  - (cd "mask" && cabal sdist)
+  - (cd "route" && cabal sdist)
+  - (cd "scribe" && cabal sdist)
+  - (cd "siggy-chardust" && cabal sdist)
+  - (cd "span" && cabal sdist)
+  - (cd "task" && cabal sdist)
+  - (cd "tasty-compare" && cabal sdist)
+  - (cd "track" && cabal sdist)
+  - (cd "units" && cabal sdist)
+  - (cd "zone" && cabal sdist)
+  - mv "build"/dist/build-flare-timing-*.tar.gz "aeson-via-sci"/dist/aeson-via-sci-*.tar.gz "aeson-via-uom"/dist/aeson-via-uom-*.tar.gz "cmd"/dist/flight-cmd-*.tar.gz "comp"/dist/flight-comp-*.tar.gz "earth"/dist/flight-earth-*.tar.gz "fsdb"/dist/flight-fsdb-*.tar.gz "gap"/dist/flight-gap-*.tar.gz "igc"/dist/flight-igc-*.tar.gz "kml"/dist/flight-kml-*.tar.gz "latlng"/dist/flight-latlng-*.tar.gz "lookup"/dist/flight-lookup-*.tar.gz "mask"/dist/flight-mask-*.tar.gz "route"/dist/flight-route-*.tar.gz "scribe"/dist/flight-scribe-*.tar.gz "siggy-chardust"/dist/siggy-chardust-*.tar.gz "span"/dist/flight-span-*.tar.gz "task"/dist/flight-task-*.tar.gz "tasty-compare"/dist/tasty-compare-*.tar.gz "track"/dist/flight-track-*.tar.gz "units"/dist/flight-units-*.tar.gz "zone"/dist/flight-zone-*.tar.gz ${DISTDIR}/
+  - cd ${DISTDIR} || false
+  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - "printf 'packages: build-flare-timing-*/*.cabal aeson-via-sci-*/*.cabal aeson-via-uom-*/*.cabal flight-cmd-*/*.cabal flight-comp-*/*.cabal flight-earth-*/*.cabal flight-fsdb-*/*.cabal flight-gap-*/*.cabal flight-igc-*/*.cabal flight-kml-*/*.cabal flight-latlng-*/*.cabal flight-lookup-*/*.cabal flight-mask-*/*.cabal flight-route-*/*.cabal flight-scribe-*/*.cabal siggy-chardust-*/*.cabal flight-span-*/*.cabal flight-task-*/*.cabal tasty-compare-*/*.cabal flight-track-*/*.cabal flight-units-*/*.cabal flight-zone-*/*.cabal\\n' > cabal.project"
+  - cat cabal.project
+  # this builds all libraries and executables (without tests/benchmarks)
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
 
-      ORIGDIR=$(pwd)
-      for dir in $PACKAGES
-      do
-        cd $dir
-        cabal check || [ "$CABALVER" == "1.16" ]
-        cabal sdist
-        PKGVER=$(cabal info . | awk '{print $2;exit}')
-        SRC_TGZ=$PKGVER.tar.gz
-        cd dist
-        tar zxfv "$SRC_TGZ"
-        cd "$PKGVER"
-        cabal configure --enable-tests
-        cabal build
-        cd $ORIGDIR
-      done
-      ;;
-  esac
-  set +ex
+  # Build with installed constraints for packages in global-db
+  - if $INSTALLED; then echo cabal new-build -w ${HC} --disable-tests --disable-benchmarks $(${HCPKG} list --global --simple-output --names-only | sed 's/\([a-zA-Z0-9-]\{1,\}\) */--constraint="\1 installed" /g') all | sh; else echo "Not building with installed constraints"; fi
 
+  # build & run tests, build benchmarks
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+  - if [ "x$TEST" = "x--enable-tests" ]; then cabal new-test -w ${HC} ${TEST} ${BENCH} all; fi
+
+  # cabal check
+  - (cd build-flare-timing-* && cabal check)
+  - (cd aeson-via-sci-* && cabal check)
+  - (cd aeson-via-uom-* && cabal check)
+  - (cd flight-cmd-* && cabal check)
+  - (cd flight-comp-* && cabal check)
+  - (cd flight-earth-* && cabal check)
+  - (cd flight-fsdb-* && cabal check)
+  - (cd flight-gap-* && cabal check)
+  - (cd flight-igc-* && cabal check)
+  - (cd flight-kml-* && cabal check)
+  - (cd flight-latlng-* && cabal check)
+  - (cd flight-lookup-* && cabal check)
+  - (cd flight-mask-* && cabal check)
+  - (cd flight-route-* && cabal check)
+  - (cd flight-scribe-* && cabal check)
+  - (cd siggy-chardust-* && cabal check)
+  - (cd flight-span-* && cabal check)
+  - (cd flight-task-* && cabal check)
+  - (cd tasty-compare-* && cabal check)
+  - (cd flight-track-* && cabal check)
+  - (cd flight-units-* && cabal check)
+  - (cd flight-zone-* && cabal check)
+
+  # haddock
+  - rm -rf ./dist-newstyle
+  - if $HADDOCK; then cabal new-haddock -w ${HC} ${TEST} ${BENCH} all; else echo "Skipping haddock generation";fi
+
+# REGENDATA ["cabal.project"]
+# EOF
